version: "2.3"

services:
    telegram_bot-container:
        image: ghcr.io/userver-framework/docker-userver-build-base:v1a
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CC
          - CCACHE_DIR=/telegram_bot/.ccache
          - CCACHE_HASHDIR
          - CCACHE_NOHASHDIR
          - CCACHE_PREFIX
          - CCACHE_SIZE
          - CMAKE_OPTS
          - CORES_DIR=/cores
          - CXX
          - MAKE_OPTS
        volumes:
          - .:/telegram_bot:rw
          - ./third_party/userver/tools/docker:/tools:ro
        ports:
          - 8080:8080
        working_dir: /telegram_bot
        entrypoint:
          - /tools/run_as_user.sh
