worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: true

server-port: 8080

secdist-path: /path/to/secdist.json
notification_time_of_day: "10:00"
notification_timezone: Europe/Moscow

chat_id: 100500
