worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is-testing: false

server-port: 8080

secdist-path: ./local_installation/etc/telegram_bot/secdist.json # change me

notification_time_of_day: "10:00" # change me
notification_timezone: Europe/Moscow # change me

chat_id: 100500 # change me
